### ISSUE TITLE
Change Log level at runtime

### ISSUE THREAD

**Issue by nigampatel** [pinojs/express-pino-logger#11]
Is there a way in pino to change Log level at runtime?

My goal is to create an endpoint where we can change log level without restarting an app.

Similar to this.
https://github.com/yannvr/Winston-dynamic-loglevel

**Comment by davidmarkclements** [comment]
hi @nigampatel see http://npm.im/pino-arborsculpture

(with thanks to @jsumners for creating it)

**Comment by jsumners** [comment]
And if you really want to emulate that Winston wrapper, all you have to do is implement an end point in your application that sets `log.level = level`.

**Comment by nigampatel** [comment]
Thank you for the quick response.

I don't have an option to use the pino-arborsculpture.  I'll try to see if I can get it work using the log.level approach.

**Comment by MarkusAnthony** [comment]
Can I get a little more info on this?
(I am relatively new to nodejs)

In server.js I:

```
const pino = require('pino');
const log = pino({ level: process.env.LOG_LEVEL || 'info' });

const expressPino = require('express-pino-logger');
const expressLogger = expressPino({ logger:log });
const app = express();

app .use(expressLogger);
```

So in "route\changelevel.js" how would I set 

> "log.level = level"

@jsumners How do I get access to log from server.js? I am assuming you are talking about the initial instantiation of pino?

-Markus

**Comment by jsumners** [comment]
I know nothing of Express. But I imagine it is attached to the request like `req.log`. So `req.log.info('foo')` would log the string "foo" and `req.log.level = 'debug'` would change the level to "debug".

**Comment by MarkusAnthony** [comment]
The level change does not persist when using the following:

```
router.get('/level/:level', async function(req, res) {
  req.log.level = req.params.level
  res.send(200, 'Update log level to: ' + req.params.level);
});

router.get('/level', async function(req, res) {
  res.send(200, 'log level: ' + req.log.level);
});

```
Markus

**Comment by medolino** [comment]
I run into the same problem today. It's a bit late to answer but anyway :)

If you want the level change to be persisted, you need to change `loggingMiddleware.logger.level`.

Here is an example, how you can do it:

```js
const express = require('express')
const bodyParser = require('body-parser')
const pinoExpress = require('express-pino-logger')

const app = express()

app.use(bodyParser.json())

const pinoExpressMiddleware = pinoExpress()

app.use(pinoExpressMiddleware)

app.route('/log-level')
  // get current log level
  .get((req, res) => {
    res.json({ level: req.log.level })
  })
  // update log level
  .put((req, res) => {
    const newLogLevel = req.body.level

    pinoExpressMiddleware.logger.level = newLogLevel

    res.json({ status: `Log level changed to ${newLogLevel}` })
  })

app.listen(3000, () => console.log('Server started.'))
```
