### ISSUE TITLE
How to not get the headers and req in logs file?

### ISSUE THREAD

**Issue by slim-hmidi** [pinojs/express-pino-logger#12]
I'm using pino for logging but the default log file contains so much data that I want to delete them such as the headers and req.
How can I do that?

**Comment by davidmarkclements** [comment]
Pass `req` and `res` serializer functions (see http://getpino.io/#/docs/API?id=pinooptions-stream)

to remove `req` simply return `undefined` from the req serializer function

for `res` you can copy and paste the stdSerializer https://github.com/pinojs/pino/blob/master/lib/serializers.js#L13 and simply remove the header key from the returned object

**Comment by slim-hmidi** [comment]
Thank you for your answer.

**Comment by mrchief** [comment]
http://getpino.io/#/docs/API?id=pinooptions-stream is a 404 now.
Same with https://github.com/pinojs/pino/blob/master/lib/serializers.js#L13

**Comment by jcw-** [comment]
See: https://getpino.io/#/docs/redaction (supports redaction or removal via config now)
