### ISSUE TITLE
Readme should alert that this library (seems to be) deprecated for pino-http

### ISSUE THREAD

**Issue by gswalden** [pinojs/express-pino-logger#13]
https://github.com/pinojs/express-pino-logger/blob/master/logger.js#L2

**Comment by gswalden** [comment]
https://github.com/pinojs/express-pino-logger/blob/master/logger.js#L2

**Comment by davidmarkclements** [comment]
Nope not deprecated 

pino-http is for node core http - it happens that for our purposes all of the code is currently the same but we use this name for discoverability, and to allow the possibility of divergence in the future
