### ISSUE TITLE
Use only the error logger and don't log every request

### ISSUE THREAD

**Issue by NicolaiSchmid** [pinojs/express-pino-logger#18]
Basically, everything is said. I want to use the pino-express-logger, but only to log errors and not every request. Is there an option to disable automatic request logging?
Where would I implement it?
Thanks for your help!

**Comment by davidmarkclements** [comment]
Do you mean HTTP error as in 5xx codes? Use a custom serialiser that checks the statusCode of the res object then logs of its >= 500

**Comment by NicolaiSchmid** [comment]
I have an express error middleware at the end of my chain, which checks if the thrown error in any of the other middlewares is user relevant. If not, I do some processing and would like to log the request object as well. Basically every information your middleware provides.
I achieved that with `request.log.error(error)` (error from the express middleware). But since I registered the `express-pino-middleware` every request is logged (even the ones that are successful), which I would like to disable.
Is there any option, or should a write some code for a PR?

**Comment by davidmarkclements** [comment]
If you wanted to make a PR you could make it against pino-http but we'd want to make sure that the option would work (and wouldn't break) the loggers that rely on it (koa-pino-logger, restify-pino-logger).

Alternatively, because what you want is very simple, you could just use pino and create a lib/logger.js file

```js
const logger = require('pino')()
module.exports = (req, res, next) => {
  req.log = res.log = logger.child({req:req})
  next()
}
```

**Comment by NicolaiSchmid** [comment]
No need to create a PR for me right now! Somehow I missed the `.child` function while I was skimming the pino docs.
**Thanks!!**
