### ISSUE TITLE
Prevent logging of every static asset

### ISSUE THREAD

**Issue by cyberwombat** [pinojs/express-pino-logger#23]
In other loggers placing the log middleware after the static middleware seems to do the trick but here I get a log entry for every image/css/js file no matter where I place the pino entry. Is there an easy way to not log static assets?

**Comment by mcollina** [comment]
The only way to do this is to put all your routes in a separate express.Router, and install the middleware there instead.

Ona a side note, we have added a feature to hapi-pino to filter based on a prefix, and it would be nice to add this here as well.

**Comment by cyberwombat** [comment]
Great. I already had a separate router component. Thanks.

**Comment by muuhoffman** [comment]
I was still struggling with this and this worked well for me in the `pino-http` or `express-pino-logger` (which just uses `pino-http`) library:
```
const expressLogger = expressPino({
  autoLogging: {
    ignorePaths: ["/_next"],
    getPath: (req) => {
      if (/_next/.test(req.url)) {
        return "/_next"
      }
      return req.url
    }
  },
});
```
