### ISSUE TITLE
Log the req/res body

### ISSUE THREAD

**Issue by cvburgess** [pinojs/express-pino-logger#24]
Hey there!

This lib is quite excellent.

Only issue: I'd love to log the req and res bodies as they contain useful information.

What is the desired way of doing this?

**Comment by mcollina** [comment]
we don't log them because they could be quite big. They are also very likely to contain personal information you might not want to log anyway. You can just log them yourself `req.log.info({ body })`.

**Comment by cvburgess** [comment]
thank you, it would be nice as an option for scenarios where you know what the bodies should contain ( like internal microservices )

**Comment by batjko** [comment]
Same here. I would like to at least have the option, say in order to hook in and log out the number of records returned.

**Comment by naseemkullah** [comment]
Would the PR be in the `pino-http` repo or in this repo? I am a bit confused by the existence of the two

**Comment by mcollina** [comment]
pino-http, thanks!

**Comment by Sof31t** [comment]
@mcollina I think giving the user the possibility to choose whatever he wants to log is important. In my use case, I don't have any huge request bodies, I want to be able to automatically log all of them. I prefer not to have more than one log for each request. Also, for sensitive information, we should be able to hide them 😄

**Comment by naseemkullah** [comment]
https://github.com/pinojs/pino-http/pull/76 created which adds the example as how to achieve logging req body

**Comment by Phunky** [comment]
@naseemkullah when trying to apply this example to `express-pino-logger` the request body does not seem to be available.

**Comment by ryan-efendy** [comment]
@naseemkullah do you have an example of logging the request body?

**Comment by naseemkullah** [comment]
@ryan-efendy from my experience with Express, https://github.com/richardschneider/express-mung was required to add the body to the res object, then followed the pattern hereby mentioned but for `res`

**Comment by naseemkullah** [comment]
@ryan-efendy answered in pinojs/pino-http#173
