### ISSUE TITLE
Identify what request caused an error

### ISSUE THREAD

**Issue by webstacker** [pinojs/express-pino-logger#34]
I'm probably missing something here.

Using `req.log.info('some info')` gives an output that contains the current request id. However, using `req.log.error(Error('something bad'))` only outputs the stack.

Is there a way to see what request caused the error?

**Comment by davidmarkclements** [comment]
that seems like a bug to me, can you provide a reproducible case inline here?

**Comment by webstacker** [comment]
@davidmarkclements  having looked at it further is appears to be an issue with [pino-pretty](https://github.com/pinojs/pino-pretty) 

Specifically, this seems to be the problem, when using it it drops the req/res properties and just outputs the stack:

https://github.com/pinojs/pino-pretty/issues/39

Adding the "`errorProps: '*'`" (as shown below) at least gets me the "req" property back, but the output looks a little funky.

```javascript
require('pino-http')({
    level: 'debug',
    prettyPrint: {
        levelFirst: true,
        colorize: true,
        translateTime: true,
        errorProps: '*'
    }
}
```
