### ISSUE TITLE
child attribute is output twice

### ISSUE THREAD

**Issue by daveisfera** [pinojs/express-pino-logger#35]
I'm using the concept described in #17 and the value that's added is logged twice. For example, `user_id: 1` appears in the output JSON twice and this looks confusing and technically isn't valid JSON.

**Comment by mcollina** [comment]
Would you mind adding a snippet? You should not be getting the `user_id`  twice following that.

Logging a property twice _can_ happen. However JSON parsers are lazy, and override the property automatically - even if it's not valid, it's a trade off we have done to increase the throughput.

**Comment by davidmarkclements** [comment]
https://getpino.io/#/docs/help?id=dupe-keys

**Comment by daveisfera** [comment]
Hmmm. It looks like something in our middleware is causing it to be added twice and that this isn't actually an issue with `express-pino-logger`
