### ISSUE TITLE
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by camlegleiter** [pinojs/express-pino-logger#39]
Node version: 12.9.1

Running with the latest version of express-pino-logger, I get DeprecationWarnings in my log output due to accessing `OutputMessage.prototype._headers`. This looks to be related to https://github.com/pinojs/pino-std-serializers/issues/23 (fixed in https://github.com/pinojs/pino-std-serializers/issues/24), which just needs to be propagated to pino-http and here.

**Comment by mcollina** [comment]
would you like to send a PR?

Il giorno mar 10 set 2019 alle ore 14:46 camlegleiter <
notifications@github.com> ha scritto:

**Comment by camlegleiter** [comment]
Do you mean for both repositories? Seems like one would need to be for pino-http to upgrade, then a second for here to upgrade pino-http version.

**Comment by mcollina** [comment]
That would be fantastic!

Il giorno mar 10 set 2019 alle ore 15:02 camlegleiter <
notifications@github.com> ha scritto:

**Comment by camlegleiter** [comment]
PR open for upgrade to pino-http: https://github.com/pinojs/pino-http/pull/71

**Comment by camlegleiter** [comment]
Well, this is embarrassing... turns out that, as @mcollina points out in the above PR that the versioning should pull in latest minor/patch versions of pino-http and pino-std-serializers. The actual issue with DeprecationWarnings was coming from a different package altogether--good thing for the `--trace-warnings` flag--and there isn't any actual issue here.

Sorry for the confusion. I'll go ahead and close this and the current open PR.
