### ISSUE TITLE
Custom log levels break autoLogging

### ISSUE THREAD

**Issue by shiftie** [pinojs/express-pino-logger#40]
Hi!

When I add `customLevels` to Pino instance & when I use these levels with `customLogLevel`, it stops `autoLogging` if custom level value is not bigger than all default levels values ( > 60 ).

**Comment by mcollina** [comment]
Can you upload a script to reproduce?

**Comment by shiftie** [comment]
can't reproduce on a minimal example, must be something in my implementation, sorry.
