### ISSUE TITLE
What are the differences with pino-http? 

### ISSUE THREAD

**Issue by gquittet** [pinojs/express-pino-logger#41]
I've seen in the code base that the only lines are
```javascript
'use strict'
module.exports = require('pino-http')
```
So I don't understand what is the utility of this library 🤔

I've installed `pino-http` on my express server and it works well.

Can you help me?

**Comment by mcollina** [comment]
None, it's just for search purposes.

**Comment by lucaspiller** [comment]
To be honest this confusing. I came across this too, and wondered the same thing. I was thinking maybe that this library has some secret sauce that hooks into express that I'm oblivious about? Plus the README has broken links and doesn't describe any of the options specific to http logging that you may want to enable - compared to https://github.com/pinojs/pino-http#pinohttpopts-stream.

I'd suggest deprecating this library and redirecting to 'pino-http' instead, or at the very least at something to make it very clear this is exactly the same thing.

**Comment by mcollina** [comment]
Would you like to send a PR?
