### ISSUE TITLE
Appending to every request.

### ISSUE THREAD

**Issue by jaredmeakin** [pinojs/express-pino-logger#42]
I'd like to append data to every request and found a workable solution in https://github.com/pinojs/express-pino-logger/issues/17 as a middleware. However, I just want to confirm that there aren't any performance implications with creating and replacing the logger, with a child instance, on every request?

The code snippet I'm referring to is:
```
 res.log = req.log = req.log.child({ })
```

Thanks!

**Comment by mcollina** [comment]
Creating a new child logger is extremely fast and the overhead should be extremely small. However, it's more code to execute so there is of course a tiny cost to it.
