### ISSUE TITLE
ignore routes

### ISSUE THREAD

**Issue by dennisevnex** [pinojs/express-pino-logger#43]
Is there a way to ignore routes from logging like `/health`?

**Comment by mcollina** [comment]
See the autoLogging.ignorePaths option: https://github.com/pinojs/pino-http/blob/master/README.md#api

**Comment by dennisevnex** [comment]
thank you

**Comment by muuhoffman** [comment]
I was still struggling with this and this worked well for me to ignore a hierarchy of paths from next.js
```
const expressLogger = expressPino({
  autoLogging: {
    ignorePaths: ["/_next"],
    getPath: (req) => {
      if (/_next/.test(req.url)) {
        return "/_next"
      }
      return req.url
    }
  },
});
```
