### ISSUE TITLE
QUESTION: pino and pino-express

### ISSUE THREAD

**Issue by artoodeeto** [pinojs/express-pino-logger#44]
Hello maintainers,

Thank you for this awesomeness. I just have a question. 

If I use `express-pino` do i still have to use `pino`?

im confused so im using it like this.

```ts
import pinoExpress from 'express-pino-logger';
import pino from 'pino';
const pins = pino();

app.use(pinoExpress({logger: pins,  prettyPrint: true }, pino.destination(path.resolve(__dirname, '../logs/route.log'))));

// some routes implementation
pins.info('test route..'); < ---- this wont be written in the filie. is this a bug?
```

**Comment by mcollina** [comment]
You are not passing `pino.destination()` to the instance of pino.

**Comment by artoodeeto** [comment]
@mcollina Hello sir. Thank you for responding. Im confused.

Do you mean like this?
```ts
const pins = pino({ prettyPrint: true }, pino.destination(path.resolve(__dirname, '../logs/route.log')));
```

but then I cant use it on express like `app.use(pins)`

**Comment by mcollina** [comment]
You need to pass the pino instance to this module.

**Comment by artoodeeto** [comment]
yea. I got it. I was just confused the way js and typescript. im closing this now. thank you.
