### ISSUE TITLE
How to find file and line that caused the error?

### ISSUE THREAD

**Issue by JeffResc** [pinojs/express-pino-logger#45]
Hello, I've just started utilizing pino and express-pino-logger for my project. I've been able to find the stack traces, but the only issue is that it doesn't list my file that caused the error and rather just the node_module file that caused it internally within express. Is it possible to find which of my files caused the error?

(For context I've removed the headers from this example as they shouldn't matter and I've ran it through pino-pretty in order to read it better)

500 Error Example:
```
[1587329487144] INFO  (5093 on paradox): request errored
    req: {
      "id": 8,
      "method": "GET",
      "url": "/stacktrace-test",
      "headers": {}
    }
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/home/jeff/NewRepo/node_modules/pino-http/logger.js:67:38)
              at emitNone (events.js:111:20)
              at ServerResponse.emit (events.js:208:7)
              at onFinish (_http_outgoing.js:720:10)
              at _combinedTickCallback (internal/process/next_tick.js:131:7)
              at process._tickCallback (internal/process/next_tick.js:180:9)
    }
    responseTime: 11
```

**Comment by JeffResc** [comment]
I just read up on #30, is it possible to get my application's stack trace rather than the internal one?

**Comment by JeffResc** [comment]
I was able to find what I needed using the following code, closing this issue but pasting it here for future reference for anyone looking for something similar:
```javascript
process.on('uncaughtException', err => {
    pino.error(err);
    process.exit(1);
  });
  process.on('unhandledRejection', err => {
    pino.error(err);
  });
app.use(function(error, req, res, next) {
    res.statusCode = 500;
    pino.error(error);
    res.render('500', {
      stack: error.stack
    });
  });
```

**Comment by michaeloryl** [comment]
This didn't catch Node runtime errors for me.  For example, a TypeErro for trying to read a property of an undefined value.  It still throws the Node error outside of Pino and the above process handlers, as well as the middleware, fail to catch it.

**Comment by mcollina** [comment]
@michaeloryl would you mind to paste an example? Given my knowledge of Node.js, that’s not possible.

**Comment by michaeloryl** [comment]
When I tried to make a small demo project, it worked for me.  I will have to work with my application more to see if I can get this to work.  Thanks.

**Comment by michaeloryl** [comment]
The issue was order.  While I had the error handling middleware as the last of the `app.use()` middleware statements, it was still before all the imported routes and direct `app.get()` statements.  Moving the error handler `app.use()` past the routes covered them.

I've got exactly what I need now.  Thanks.
