### ISSUE TITLE
Exclude specific URLs from pino logs

### ISSUE THREAD

**Issue by cseas** [pinojs/express-pino-logger#52]
My server uses `/healthz` endpoints which I need to tell pino to ignore, not sure how.

This feature has already been requested in https://github.com/pinojs/hapi-pino/issues/26 and https://github.com/pinojs/koa-pino-logger/issues/23

Perhaps something like `ignorePaths` should just be added to the main pino package since this is a general issue and not specific to a particular server library.

**Comment by cseas** [comment]
Nevermind, just found an answer here:
https://github.com/pinojs/express-pino-logger/issues/43

Would it be possible to mention the solution somewhere in the [pino docs](http://getpino.io/)?
Searching for "ignore" there didn't give any useful results.

This is just feedback. I found the solution so the maintainers can close this issue once they see it.

**Comment by mcollina** [comment]
Would you like to send a PR?
