### ISSUE TITLE
Update new pino-http version

### ISSUE THREAD

**Issue by HellCatVN** [pinojs/express-pino-logger#53]
Update New version of pino-http so that it can using regex when using pathIgnore :
https://github.com/pinojs/pino-http/pull/100

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by HellCatVN** [comment]
I think you misunderstand my open issue cause I suggest dev team to update new version of pino-http cause in this package we using older once which is not support regex yet
