### ISSUE TITLE
Clarify this is just a "clone" of pino-http

### ISSUE THREAD

**Issue by janLuke** [pinojs/express-pino-logger#59]
**Update:** 
Nevermind, I found https://github.com/pinojs/express-pino-logger/issues/41.
Not to be harsh, but it blows my mind that nobody thought it was a good idea to mention that this project is just for search purposes in the README.

---
**Original questions:**
Can you please explain how this package differs from `pino-http`? And why it is not mentioned in [pino/Using with Express](https://github.com/pinojs/pino/blob/master/docs/web.md#express)?

Thank you.

**Comment by mcollina** [comment]
Would you like do send a PR?

**Comment by janLuke** [comment]
I think you can describe your project better than I could. And it would take less time than reviewing my PR.
