### ISSUE TITLE
Ability to mask or remove the Authorization header

### ISSUE THREAD

**Issue by dlbrown06** [pinojs/express-pino-logger#8]
It would be nice to provide additional configuration to define what headers you would like removed or masked when logging. For example, the Authorization header which you might not want included in the logs.

**Comment by mcollina** [comment]
Would you like to send a PR? We are already tracking this in https://github.com/pinojs/pino-http/issues/13.

It's a matter of wiring things up with https://www.npmjs.com/package/pino-noir.

**Comment by brandongoode** [comment]
For anyone that's looking for a solution, this is what I used:

```js
const noir = require('pino-noir');

const redaction = noir(
  {
    req: require('express-pino-logger').stdSerializers.req,
    res: require('pino').stdSerializers.res,
    err: require('pino').stdSerializers.err,
  },
  ['req.headers.authorization']
);

const expressPino = require('express-pino-logger')({
  serializers: redaction
})
```

**Comment by mcollina** [comment]
Closing, as it seem to be solved!
