### ISSUE TITLE
Upgrade pino-http dependency to 6.0.0

### ISSUE THREAD

**Issue by AndreSilva1993** [pinojs/express-pino-logger#86]
Since Pino v7 was launched the custom serializers for express-pino-logger have stopped working and every detail from the request gets logged which is not ideal. The pino-http. 6.0.0 already upgraded their Pino v7 inner dependency.

<img width="913" alt="Screenshot 2021-11-17 at 10 36 24" src="https://user-images.githubusercontent.com/10833491/142185060-866a3a0d-8407-4b3c-848b-df23dbc94edb.png">

I already can see that master has the latest pino-http version so is this migration process in the works?

**Comment by mcollina** [comment]
I will assemble a release

**Comment by AndreSilva1993** [comment]
When are you planning on releasing?

**Comment by mcollina** [comment]
Released as v7.0.0
